apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstwings-web
  namespace: firstwings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firstwings-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: firstwings-web
      annotations:
         configHash: "4afd74ac842b5a83015cb45cc0b26b17ad1fe7baf1be3ed527615b6bb887b411"
    spec:
      volumes:
        - name: webapp-data
          emptyDir: {}
        - name: laravel-cronjob
          configMap:
            name: laravel-cronjob
        - name: unit-config
          configMap:
            name: unit-config
      containers:
      - name: unit
        image: registry.digitalocean.com/vatsim-containers/laravel-nginx-unit-base
        imagePullPolicy: Always
        volumeMounts:
        - name: webapp-data
          mountPath: "/var/www/app"
        - name: unit-config
          mountPath: "/docker-entrypoint.d"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: laravel-config
        env:
          - name: CONFIG_HASH
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['configHash']
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
      - name: cronjob
        image: registry.digitalocean.com/vatsim-containers/cronjob-base
        imagePullPolicy: Always
        volumeMounts:
        - name: laravel-cronjob
          mountPath: "/var/spool/cron/crontabs"
        - name: webapp-data
          mountPath: "/var/www/app"
      initContainers:
      - name: web-data
        image: registry.digitalocean.com/vatsim-containers/bmac
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "cp -var /app/* /data"]
        volumeMounts:
        - name: webapp-data
          mountPath: "/data"
      imagePullSecrets:
      - name: vatsim-containers
