apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
  labels:
    name: laravel-config
  namespace: firstwings
data:
  APP_NAME: "Laravel"
  APP_ENV: "local"
  APP_KEY: "44b077bc5e291e2e5f7c478f04fe0f0e"
  APP_DEBUG: "true"
  APP_URL: "http://localhost:31386"
  BUGSNAG_API_KEY: ""
  MIX_BUGSNAG_API_KEY: ""
  LOG_CHANNEL: "stack"
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: "debug"
  DB_CONNECTION: "mysql"
  DB_HOST: "firstwings-mysql"
  DB_PORT: "3306"
  DB_DATABASE: "homestead"
  DB_USERNAME: "homestead"
  DB_PASSWORD: "secret"
  DB_TABLE_PREFIX: ""
  DB_LOWER_STRING_LENGTH: "false"
  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "file"
  SESSION_DRIVER: "file"
  SESSION_LIFETIME: "120"
  QUEUE_CONNECTION: "sync"
  MEMCACHED_HOST: "127.0.0.1"
  REDIS_HOST: "firstwings-redis"
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"
  MAIL_MAILER: "smtp"
  MAIL_HOST: "mailhog"
  MAIL_PORT: "1025"
  MAIL_USERNAME: "null"
  MAIL_PASSWORD: "null"
  MAIL_ENCRYPTION: "null"
  MAIL_FROM_ADDRESS: "null"
  MAIL_FROM_NAME: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_BUCKET: ""
  AWS_USE_PATH_STYLE_ENDPOINT: "false"
  PUSHER_APP_ID: ""
  PUSHER_APP_KEY: ""
  PUSHER_APP_SECRET: ""
  PUSHER_APP_CLUSTER: "mt1"
  MIX_PUSHER_APP_KEY: ""
  MIX_PUSHER_APP_CLUSTER: ""
  OAUTH_BASE: "https://auth-dev.vatsim.net"
  OAUTH_CLIENT: "476"
  OAUTH_SECRET: "f7IWEPcPaOYtFZOf1TBUMV3XupSM3qAluJzqTBRY"
  OAUTH_MAPPING_CID: "data-cid"
  OAUTH_MAPPING_FIRSTNAME: "data-personal-name_first"
  OAUTH_MAPPING_LASTNAME: "data-personal-name_last"
  OAUTH_MAPPING_EMAIL: "data-personal-email"
  SITE_TITLE: "Booking"
  SITE_DIVISION: "Divsion Name"
  SITE_DIVISION_URL: "https://division.org"
  SITE_CONTACT_MAIL: "event@division.org"
  SITE_PILOTBRIEF_URL: "https://www.division.org/visiting-pilots/"
  SITE_CHARTS_URL: "https://www.division.org/charts/"
  BOOTSTRAP_COLOR_PRIMARY: "#2C3E50"
  BOOTSTRAP_COLOR_SECONDARY: "#95a5a6"
  BOOTSTRAP_COLOR_TERTIARY: "#18BC9C"
  BOOTSTRAP_COLOR_SUCCESS: "#18BC9C"
  BOOTSTRAP_COLOR_DANGER: "#E74C3C"
  BOOTSTRAP_COLOR_WARNING: "#F39C12"
  ACTIVITY_LOGGER_ENABLED: "true"
  TELESCOPE_ENABLED: "false"
  IGNITION_EDITOR: "vscode"
  IGNITION_THEME: "auto"
  IGNITION_REMOTE_SITES_PATH: ""
  IGNITION_LOCAL_SITES_PATH: ""
