apiVersion: v1
kind: Service
metadata:
  labels:
    name: firstwings-web
  name: firstwings-web
  namespace: firstwings
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: firstwings-web
